### ISSUE TITLE
MVP and Schema Issues

### ISSUE THREAD

**Issue by OhBall** [kangaree/fullscreend#1]
MVP's look good!

- [x] A more semantic name for `shows_users` would probably be better. Something to the point, like `watch_statuses`.

- [x] Let's talk tomorrow about outside API's.

**Comment by kangaree** [comment]
Great! Love to talk about outside API's, especially to seed my database. I really want to use it to see if I can seed the data I need, so I'd love it if you could help me navigate this page:

https://api.thetvdb.com/swagger

I understand the routes, but I don't know how to apply my api key to get all of the info I want. 

Yes, watch_statuses works way better. Thanks!
