### ISSUE TITLE
Issues 1/28

### ISSUE THREAD

**Issue by OhBall** [kangaree/fullscreend#10]
Because I want you to keep moving forward, some of the auth related issues can be put off for now, but I want to make sure that you're aware of them so that you can go back and fix them later.

- [x] Sometimes the description text on shows is too long, and it gets covered up by the footer.

- [x] Submit button on the sign up form should have a border-radius.

- [x] Padding on the bottom of the sign-up form should be slightly larger.

- [x] Sign-in button overlaps with form fields.

- [x] `Testing?` button should probably just say something along the lines of `guest user`.

- [x] Search results dropdown needs styling.

- [x] Currently no search index.

**Comment by kangaree** [comment]
How would you approach a search index? I'm having trouble connecting how I'd press enter, and another page would be rendered.
