### ISSUE TITLE
Frontend State Issues

### ISSUE THREAD

**Issue by OhBall** [kangaree/fullscreend#2]
Things are looking good, but I think a bit of a refactor is in order. The main thing that's missing is connective tissue between resources using arrays of ids. To expand on that: in our frontend, we don't need to have a slice of state for join tables. For instance, instead of having a whole slice of state for `listings` we can instead use our `listings` on the backend to generate an array of `show_ids` for lists and potentially `list_ids` for shows. This way, instead of having to redo the join on the frontend every time that our state changes, a list can just use its `show_ids` array to quickly fetch exactly what it needs from the `shows` slice of state.

**Comment by kangaree** [comment]
Thanks for the feedback! I agree that the frontend state should not have a slice of the join tables, rather an array of ids. 

I've corrected my sample state schema. Please let me know if other parts of my proposal need fixing.
